DEBUG?=0

MK:=mkdir
RM:=rm -r

ifeq ($(DEBUG),1)
NO_ECHO:=
else
NO_ECHO:=@
endif

ifneq (,$(filter clean, $(MAKECMDGOALS)))

OTHER_GOALS=$(filter-out clean,$(MAKECMDGOALS))

ifneq (,$(OTHER_GOALS))
$(info Cannot make anything in parallel with "clean".)
$(info Execute "$(MAKE) clean \
  $(foreach goal, $(OTHER_GOALS),&& $(MAKE) $(goal))" instead.)
$(error Cannot continue)
else  # else OTHER_GOALS
.PHONY: clean

clean:
	$(NO_ECHO)echo "remove $(OUTPUT_PROJ_DIR)"
	$(NO_ECHO) $(RM) $(OUTPUT_PROJ_DIR)

endif # end OTHER_GOALS

else # else not clean

PLATFORM_SUFFIX := $(if $(filter Windows%,$(OS)),windows,posix)
TOOLCHAIN_CONFIG_FILE := Makefile.$(PLATFORM_SUFFIX)
include $(TOOLCHAIN_CONFIG_FILE)

# $1 path
define quote
'$(subst ','\'',$(1))'
endef

# Toolchain commands
CC      := $(call quote,$(GNU_INSTALL_ROOT)$(GNU_PREFIX)-gcc)
CXX     := $(call quote,$(GNU_INSTALL_ROOT)$(GNU_PREFIX)-c++)
AS      := $(call quote,$(GNU_INSTALL_ROOT)$(GNU_PREFIX)-as)
AR      := $(call quote,$(GNU_INSTALL_ROOT)$(GNU_PREFIX)-ar) -r
LD      := $(call quote,$(GNU_INSTALL_ROOT)$(GNU_PREFIX)-ld)
NM      := $(call quote,$(GNU_INSTALL_ROOT)$(GNU_PREFIX)-nm)
OBJDUMP := $(call quote,$(GNU_INSTALL_ROOT)$(GNU_PREFIX)-objdump)
OBJCOPY := $(call quote,$(GNU_INSTALL_ROOT)$(GNU_PREFIX)-objcopy)
SIZE    := $(call quote,$(GNU_INSTALL_ROOT)$(GNU_PREFIX)-size)
$(if $(shell $(CC) --version),,$(info Cannot find: $(CC).) \
  $(info Please set values in: "$(abspath $(TOOLCHAIN_CONFIG_FILE))") \
  $(info according to the actual configuration of your system.) \
  $(error Cannot continue))


# $1 : target name
# $2 : source file
define get_object_file_name
$(OUTPUT_PROJ_DIR)/$(strip $(1))/$(notdir $(2:%.s=%.s.o)).o
endef

# $1 : prefix name
# $2 : target name
define target_specific
$($(addsuffix _$(strip $(2)),$(1)))
endef

# $1 : target name
# $2 : object file
# $3 : source file
define bind_src_with_obj
$(eval $(2) 	:= $(3))\
$(eval $(2)_TGT	:= $(1))\
$(eval $(2): Makefile | $(dir $(2)).)
endef

# $1 : target name
# $2 : list source file
define get_object_file
$(foreach src_file, $(2),\
	$(eval obj_file:=$(call get_object_file_name,$(1),$(src_file)))\
	$(DEPENDENCES += $(obj_file:%.o=%.d))\
	$(call bind_src_with_obj,$(1),$(obj_file),$(src_file))\
	$(obj_file))
endef

# $1 : target name
# $2 : list include folder
define get_inc_paths
$(foreach inc,$(2),-I$(inc))
endef

INC_PATHS=$(call target_specific,INC_PATHS,$($@_TGT))


# $1 : target name
# $2 : file output
define prepare_build
$(eval DEPENDENCES:=)\
$(eval $(2): \
	$(call get_object_file, $(1),\
		$(SRC_FILES) $(call target_specific,SRC_FILES,$(1))))\
$(eval -include $(DEPENDENCES))\
$(eval INC_PATHS_$(strip $(1)) :=\
	$(call get_inc_paths,$(1),\
		$(INC_FOLDER) $(call target_specific,INC_FOLDER,$(1))))
endef


# $1 : target name
define define_target
$(eval OUTPUT_FILE := $(OUTPUT_PROJ_DIR)/$(strip $(1)))\
$(eval $(1): $(OUTPUT_FILE).out $(OUTPUT_FILE).hex $(OUTPUT_FILE).bin\
			; $(NO_ECHO)echo DONE $(1))\
$(call prepare_build,$(1),$(OUTPUT_FILE).out)
endef


# $1 : toolchain 
# $2 : flag
# $3 : 
define run
$(info $(3) file : $(notdir $($@)))\
$(NO_ECHO) $(1) -MD -MP -c -o $@ $($@) $(2) $(INC_PATHS)
endef


.PHONY: $(TARGETS) all

all: $(TARGETS)

$(OUTPUT_PROJ_DIR):
	$(MK) $@
$(OUTPUT_PROJ_DIR)/%/.: | $(OUTPUT_PROJ_DIR)
	cd $(OUTPUT_PROJ_DIR) && $(MK) $*

%.c.o:
	$(call run,$(CC) -std=c99, $(CCFLAG), Compiling)

%.cpp.o:
	$(call run,$(CC), $(CCFLAG) $(CXXFALG), Compiling)

%.S.o %.s.o.o: 
	$(call run,$(CC) -x assembler-with-cpp, $(ASMFLAGS), Assembling)


%.out:
	$(info Link target : $@)
	$(NO_ECHO) $(CC) $(LDFLAGS) $(LIB_FILES) $^ -Wl,-Map=$(@:.out=.map) -o $@
	$(NO_ECHO) $(SIZE) $@

%.hex: %.out
	$(info prepare hex : $@)
	$(NO_ECHO) $(OBJCOPY) -O ihex $< $@

%.bin: %.out
	$(info prepare bin : $@)
	$(NO_ECHO) $(OBJCOPY) -O binary $< $@

endif

