


#define NRFX_UART_ENABLED 1

#define NRFX_UART0_ENABLED 1

#define NRF_LOG_ENABLED 0

#define NRF_LOG 0

#define NRFX_GPIOTE_ENABLED 1
#define NRFX_GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 1
#define NRFX_GPIOTE_CONFIG_IRQ_PRIORITY 6
